import argparse
import logging
import os
import pickle

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix

import src.config as config

logger = logging.getLogger(__name__)


def plot_confusion_matrix(y_true, y_pred, class_names, output_path):
    """
    Generates and saves a confusion matrix heatmap.
    """
    labels = list(range(len(class_names)))
    cm = confusion_matrix(y_true, y_pred, labels=labels)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names)
    plt.title('Confusion Matrix')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.tight_layout()
    plt.savefig(output_path)
    logger.info(f"Confusion matrix saved to {output_path}")
    plt.close()


def main(pkl_path, output_dir):
    """
    Loads predictions, calculates metrics, and saves the results.
    """
    os.makedirs(output_dir, exist_ok=True)

    logger.info(f"Loading predictions from {pkl_path}")
    with open(pkl_path, 'rb') as f:
        results_list = pickle.load(f)
    df = pd.DataFrame(results_list)

    if df.empty:
        logger.error("The predictions file is empty. Cannot generate evaluation.")
        return

    y_true = df['true_label']
    y_pred = df['predicted_label']
    class_names = getattr(config, "CLASS_NAMES", ["safe", "not_safe", "kiss"])

    # --- Generate and Save Classification Report ---
    report = classification_report(y_true, y_pred, target_names=class_names, digits=4,
                                   labels=list(range(len(class_names))))
    report_path = os.path.join(output_dir, "classification_report.txt")

    logger.info("\n--- Classification Report ---")
    print(report)
    with open(report_path, 'w') as f:
        f.write(report)
    logger.info(f"Classification report saved to {report_path}")

    # --- Generate and Save Confusion Matrix ---
    cm_path = os.path.join(output_dir, "confusion_matrix.png")
    plot_confusion_matrix(y_true, y_pred, class_names, cm_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate model predictions from a pickle file.")
    parser.add_argument("--pkl_path", type=str, required=True,
                        help="Path to the predictions.pkl file generated by predict.py.")
    parser.add_argument("--save_dir", type=str, required=True, help="Directory to save evaluation results.")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    main(args.pkl_path, args.save_dir)
